language: elixir
sudo: false
elixir:
  - 1.8
  - 1.9
otp_release:
  - 21.0
  - 22.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 18.3
    - elixir: 1.9
      otp_release: 18.3
    - elixir: 1.8
      otp_release: 19.1
    - elixir: 1.9
      otp_release: 19.1
    - elixir: 1.9
      otp_release: 20.0
env:
  - MIX_ENV=test
script:
  - mix eqc.install --mini
  - mix coveralls.travis
notifications:
  recipients:
    - paulschoenfelder@fastmail.com
