name: elixir

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - otp: '24.2'
            elixir: '1.12.3'

          - otp: '25.0'
            elixir: '1.13.3'

          - otp: '27.2'
            elixir: '1.18.1'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
